### ISSUE TITLE
NullPointerException occurs when there are no pages

### ISSUE THREAD

**Issue by jack-bradshaw** [jack-bradshaw/SlidingIntroScreen#4]
Bug detected in module 'testapp' when testing the default behaviour. If an activity returns an empty collection from IntroActivity.generatePages(Bundle), it will crash when launched. The stack trace from such a crash is:

``` xml
06-07 17:28:55.637 2876-2876/com.matthewtamlin.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.matthewtamlin.testapp, PID: 2876
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.matthewtamlin.testapp/com.matthewtamlin.testapp.TestDefaults}: java.lang.IndexOutOfBoundsException
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.IndexOutOfBoundsException
                                                                             at com.matthewtamlin.sliding_intro_screen_library.indicators.DotIndicator.setSelectedItem(DotIndicator.java:468)
                                                                             at com.matthewtamlin.sliding_intro_screen_library.core.IntroActivity.regenerateProgressIndicator(IntroActivity.java:633)
                                                                             at com.matthewtamlin.sliding_intro_screen_library.core.IntroActivity.onCreate(IntroActivity.java:321)
                                                                             at android.app.Activity.performCreate(Activity.java:6237)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by jack-bradshaw** [comment]
Fixed by merging branch bug/00004 into master.
